Fixes alaa mashkouk
dimaserd/PlayTennisApp pull request #40
Opened 2024-08-14 13:20 UTC by AlaaGitHub2020

2024-08-18 21:06 UTC, dimaserd requested changes

2024-08-18 21:06 UTC, dimaserd commented on mobile/play_tennis/lib/app/main/widgets/images/CrocoAppImage.dart
> +    this.fromTournamentGameToSelect = false,
А зачем это свойство?

2024-08-18 21:06 UTC, dimaserd commented on mobile/play_tennis/pubspec.yaml
> +  #  image_cropper: ^5.0.0
Уберите комментарии, оставьте только те библиотеки, которые используются и актуальные

2024-08-18 21:15 UTC, AlaaGitHub2020 commented on mobile/play_tennis/lib/app/main/widgets/images/CrocoAppImage.dart
> +    this.fromTournamentGameToSelect = false,
потому что эффект, который произвел добавленный мной код, был реализован только на изображении, отображаемом в списке "Турниры", поэтому я просто добавил это небольшое условие, чтобы не влиять на другие области, в которых вы используете виджет (ImageViewWidget)

2024-08-19 09:41 UTC, AlaaGitHub2020 commented on mobile/play_tennis/pubspec.yaml
> +  #  image_cropper: ^5.0.0
done

2024-08-19 09:41 UTC, AlaaGitHub2020 commented on mobile/play_tennis/lib/app/main/widgets/images/CrocoAppImage.dart
> +    this.fromTournamentGameToSelect = false,
done

2024-08-24 11:52 UTC, dimaserd requested changes

2024-08-24 11:53 UTC, dimaserd requested changes

2024-08-24 11:53 UTC, dimaserd commented on mobile/play_tennis/lib/app/main/widgets/images/ImageViewWidget.dart
> +        return Image.memory(correctedBytes, width: 350, height: 500);
Думаю в этом проблема той ошибки

2024-08-25 13:34 UTC, merged